Issue #362: The script 'unittest_batch' should abort when a test is failing.

diff --git a/tools/splitobs/unittest_batch b/tools/splitobs/unittest_batch
--- a/tools/splitobs/unittest_batch
+++ b/tools/splitobs/unittest_batch
@@ -24,6 +24,7 @@ set -x
 HOST_TO_SUBMIT=${HOST_TO_SUBMIT:-${TRUE_HOST}}
 
 for test2run in ${TESTS2RUN}; do
+    statusfile=${PWD}/status_${CI_BUILD_ID}
     cat > ${TMPDIR}/splitobs_unittest_${test2run} <<EOF
 #!/bin/bash
 
@@ -43,15 +44,25 @@ fi
 echo test2run=${test2run}
 ./unittest ${test2run}
 
+rm ${statusfile}
 EOF
 
     cat ${TMPDIR}/splitobs_unittest_${test2run}
     chmod +x ${TMPDIR}/splitobs_unittest_${test2run}
 
+    touch ${statusfile}
+
     jobname=splitobs_unittest_${test2run}
     jobid=$(ord_soumet ${TMPDIR}/splitobs_unittest_${test2run} -jn ${jobname} -mach ${HOST_TO_SUBMIT} -m 32G -w 240 -listing ${PWD} -cpus ${CPUS:-1})
+    rm ${TMPDIR}/splitobs_unittest_${test2run}
+
     ${toplevel}/tools/misc/wait_for_job.sh ${jobname} ${jobid} ${host}
 
-    rm ${TMPDIR}/splitobs_unittest_${test2run}
+    if [ -f "${statusfile}" ]; then
+        echo "Some test did abort!"
+        exit 1
+    else
+        echo "All the tests have been successfully run for '${test2run}'"
+    fi
 done
 
