Issue #680: midas_build abort on failing config

diff --git a/src/midas_build b/src/midas_build
--- a/src/midas_build
+++ b/src/midas_build
@@ -54,9 +54,15 @@ if [ ! "${ORDENV_PLAT}" = rhel-8-icelake-64 ];then
   exit 1
 fi
 __midas_dot_cfg=${__here}/config.dot.sh
-source ${__midas_dot_cfg}  &> .tmp.config.out || echo "An error occured in the build configuration"
 __listing_config=${MIDAS_COMPILE_JOBNAME}.config-${__date}.out
 __listing_frontend=${MIDAS_COMPILE_JOBNAME}.${MIDAS_COMPILE_FRONTEND}-${__date}.out
+echo "Sourcing MIDAS build configuration <<< ${__midas_dot_cfg}"
+source ${__midas_dot_cfg}  &> .tmp.config.out
+if [ ! $? -eq 0 ]; then
+  mv .tmp.config.out ${__listing_config}
+  echo "An error occured in the build configuration, consult ${__listing_config}"
+  exit 1
+fi
 mv .tmp.config.out ${__listing_config}
 
 __abs_all=$(ls programs/*.f90 | sed 's/programs\/\(.*\).f90/\1/' )
