gfortran: Add option '--compiler' to 'midas_build' and 'config.dot.sh'

diff --git a/src/midas_build b/src/midas_build
--- a/src/midas_build
+++ b/src/midas_build
@@ -75,6 +75,16 @@ __abs_all="${__abs_all} ${__abs_external}"
 
 __abs_exist_list=${__abs_all}
 
+function default_compiler {
+    if [ "${ORDENV_PLAT}" = rhel-8-icelake-64 ]; then
+        echo inteloneapi-2022.1.2
+    else
+        echo "midas_build: This platform '${ORDENV_PLAT}' is not supported.  Only 'rhel-8-icelake-64' is." >&2
+        exit 1
+    fi
+}
+compiler=$(default_compiler)
+
 __fresh_build_directory=--fresh
 ## When using 'midas_build', we want verbose compilation listing
 ## This can be overriden with '--no-verbose' option
@@ -85,6 +95,7 @@ function print_usage {
 
     echo "midas_build: "
     echo "        -d|-debug|--debug: compile using the debug options (override the variable 'MIDAS_COMPILE_ADD_DEBUG_OPTIONS')"
+    echo "        --compiler: set the compiler to use (default is $(default_compiler))"
     echo "        --opt-report: add the compiler options to output the optimization report (override the variable 'MIDAS_COMPILE_OPTIMIZE_REPORT')"
     echo "        --vtune: activate the compiler options to allow 'vtune' to profile the code"
     echo "        --codecov: activate the code covering compiler options (needs a directory for storing the code coverage information) (override the variable 'MIDAS_COMPILE_CODECOVERAGE_DATAPATH')"
@@ -103,7 +114,21 @@ if [ $# -gt 0 ]; then
 
         if [[ "${arg}" = -d || "${arg}" = -debug || "${arg}" = --debug ]]; then
             export MIDAS_COMPILE_ADD_DEBUG_OPTIONS=yes
-        elif [[ "${arg}" = --opt-report ]]; then
+        elif [[ "${arg}" = --compiler ]]; then
+            if [[ $# -lt 2 ]]; then
+                echo "midas_build: The option '--compiler' must be followed by a compiler identificator" >&2
+                exit 1
+            elif [[ ${2} = -* || -z "${2}" ]]; then
+                echo "midas_build: The option '--compiler' must be followed by a compiler identificator" >&2
+                exit 1
+            fi
+            compiler=${2}
+            if [ "${compiler}" = list ]; then
+                echo "midas_build: The compiler supported are 'inteloneapi-2022.1.2' and 'gnu-14.2.0'."
+                exit 0
+            fi
+            shift
+       elif [[ "${arg}" = --opt-report ]]; then
             export MIDAS_COMPILE_OPTIMIZE_REPORT=yes
         elif [[ "${arg}" = --optreport ]]; then
             echo "midas_build: use '--opt-report' instead of '--optreport'" >&2
@@ -140,7 +165,7 @@ if [ $# -gt 0 ]; then
             export MIDAS_COMPILE_APPEND_VERSION_ID_BUILDDIR=true
         elif [[ "${arg}" = -h || "${arg}" = -help || "${arg}" = --help ]]; then
             print_usage
-            exit 1
+            exit 0
         elif [[ "${arg}" = -* ]]; then
             echo "midas_build: this option '${arg}' is not allowed" >&2
             if [[ "${arg}" = --code-cov ]]; then
@@ -196,17 +221,19 @@ fi
 __midas_dot_cfg=${__here}/config.dot.sh
 echo "Sourcing MIDAS build configuration <<< ${__midas_dot_cfg}"
 __midas_source_config_status__=0
-source ${__midas_dot_cfg} --cmake --no-show-instructions ${__fresh_build_directory} &> ${__here}/.tmp.config.out || __midas_source_config_status__=1
+source ${__midas_dot_cfg} --compiler ${compiler} --cmake --no-show-instructions ${__fresh_build_directory} &> ${__here}/.tmp.config.out || __midas_source_config_status__=1
 
 __listing_config=${__here}/${MIDAS_COMPILE_JOBNAME}.config-${__date}.out
-__listing_frontend=${__here}/${MIDAS_COMPILE_JOBNAME}.${MIDAS_COMPILE_FRONTEND}-${__date}.out
+mv ${__here}/.tmp.config.out ${__listing_config}
+
 if [ "${__midas_source_config_status__}" -ne 0 ]; then
-    mv ${__here}/.tmp.config.out ${__listing_config}
-    echo "An error occured in the build configuration, consult ${__listing_config}"
+    echo "An error occured in the build configuration!"
+    cat ${__listing_config}
+    rm ${__listing_config}
     exit 1
 fi
 
-mv ${__here}/.tmp.config.out ${__listing_config}
+__listing_frontend=${__here}/${MIDAS_COMPILE_JOBNAME}.${MIDAS_COMPILE_FRONTEND}-${__date}.out
 
 cd ${__here}
 
