Issue #695: uncommenting error detection
- reactivating compilation error and warning detection as-is
  (no reason the same compiler would output differently)
- some simple testing with introduced bugs indicates it works as-is

diff --git a/src/midas_build b/src/midas_build
--- a/src/midas_build
+++ b/src/midas_build
@@ -360,46 +360,45 @@ mv ${__listing_config} ${__listing_frontend}
 ##=========================================================
 ## Checking if compilation and linking have been successful
 
-# @TODO uncomment and adapt
-#typeset __remarks=0
-### Check for unused variables
-#typeset __remark_unused_variables=$(grep 'remark #7712: ' ${__listing_frontend} | sort -u)
-#if [ -n "${__remark_unused_variables}" ]; then
-#    echo
-#    echo "<!> Some unused variables have been found.  Would you please remove them?"
-#    echo
-#    echo "${__remark_unused_variables}"
-#    __remarks=1
-#fi
-#
-#typeset __warnings=0
-### Check for unused variables
-#typeset __warnings_all=$(grep -v '^icc: warning #10237: -lcilkrts linked in dynamically, static library not available$' ${__listing_frontend} | grep -A 2 'warning #')
-#if [ -n "${__warnings_all}" ]; then
-#    echo
-#    echo "<!> Some compiling warnings have been triggered."
-#    echo
-#    echo "${__warnings_all}"
-#    __warnings=1
-#fi
-#
-#if [ -z "${__remark_unused_variables}" -a -z "${__warnings_all}" ]; then
-#    echo
-#    echo "No compilation warnings has been detected!"
-#fi
-#
-### regex elements to find errors
-#typeset __err_regex='error #|(?<!-)undefined|make.*Circular|[Ff]ailed| Error '
-#
-#typeset __err_comp=0
-#typeset __err_front=$(grep -Pn "${__err_regex}" ${__listing_frontend})
-#if [ -n "${__err_front}" ]; then
-#    echo
-#    echo "<!> some error found in ${__listing_frontend}"
-#    echo "${__err_front}"
-#    __err_comp=1
-#    exit 1
-#fi
+typeset __remarks=0
+## Check for unused variables
+typeset __remark_unused_variables=$(grep 'remark #7712: ' ${__listing_frontend} | sort -u)
+if [ -n "${__remark_unused_variables}" ]; then
+    echo
+    echo "<!> Some unused variables have been found.  Would you please remove them?"
+    echo
+    echo "${__remark_unused_variables}"
+    __remarks=1
+fi
+
+typeset __warnings=0
+## Check for unused variables
+typeset __warnings_all=$(grep -v '^icc: warning #10237: -lcilkrts linked in dynamically, static library not available$' ${__listing_frontend} | grep -A 2 'warning #')
+if [ -n "${__warnings_all}" ]; then
+    echo
+    echo "<!> Some compiling warnings have been triggered."
+    echo
+    echo "${__warnings_all}"
+    __warnings=1
+fi
+
+if [ -z "${__remark_unused_variables}" -a -z "${__warnings_all}" ]; then
+    echo
+    echo "No compilation warnings has been detected!"
+fi
+
+## regex elements to find errors
+typeset __err_regex='error #|(?<!-)undefined|make.*Circular|[Ff]ailed| Error '
+
+typeset __err_comp=0
+typeset __err_front=$(grep -Pn "${__err_regex}" ${__listing_frontend})
+if [ -n "${__err_front}" ]; then
+    echo
+    echo "<!> some error found in ${__listing_frontend}"
+    echo "${__err_front}"
+    __err_comp=1
+    exit 1
+fi
 
 ##========================================================
 ##  Verification of installed programs
