Issue #457: dry-run first to test target in midas_build

diff --git a/src/midas_build b/src/midas_build
--- a/src/midas_build
+++ b/src/midas_build
@@ -85,6 +85,8 @@ function abs_path {
 ## some prior defitions 
 typeset __target
 typeset __job
+typeset __job_opt
+typeset __job_test_target
 typeset __job_header
 typeset __here
 typeset __abs_exist_list
@@ -112,14 +114,35 @@ mv .tmp.config.out ${__listing_config}
 if [ $# -eq 0 ]
 ## default: make all 
 then 
+    __target='all'
     __abs_exist_list=$(ls programs/*.f90 | sed 's/programs\/\(.*\).f90/\1/' )
-    __job="make all -j ${MIDAS_COMPILE_NCORES} -O  MIDAS_COMPILE_DIR_MAIN=${MIDAS_COMPILE_DIR_MAIN} MIDAS_COMPILE_ADD_DEBUG=${MIDAS_COMPILE_ADD_DEBUG} MIDAS_COMPILE_COMPF_GLOBAL=${MIDAS_COMPILE_COMPF_GLOBAL} MIDAS_COMPILE_VERBOSE=${MIDAS_COMPILE_VERBOSE}"
 else
     __target=$@
     __abs_exist_list=$(echo ${__target} | tr -s ' ' '\n'  | grep '.Abs' | sed 's/\.Abs//' | column )
     ## ^ there must be a simpler solution
-    __job="make ${__target} -j ${MIDAS_COMPILE_NCORES} -O  MIDAS_COMPILE_DIR_MAIN=${MIDAS_COMPILE_DIR_MAIN} MIDAS_COMPILE_ADD_DEBUG=${MIDAS_COMPILE_ADD_DEBUG} MIDAS_COMPILE_COMPF_GLOBAL=${MIDAS_COMPILE_COMPF_GLOBAL} MIDAS_COMPILE_VERBOSE=${MIDAS_COMPILE_VERBOSE}"
 fi
+
+##=========================================================
+## testing target validity on frontend first
+
+__job_opt="-O MIDAS_COMPILE_DIR_MAIN=${MIDAS_COMPILE_DIR_MAIN} MIDAS_COMPILE_ADD_DEBUG=${MIDAS_COMPILE_ADD_DEBUG} MIDAS_COMPILE_COMPF_GLOBAL=${MIDAS_COMPILE_COMPF_GLOBAL} MIDAS_COMPILE_VERBOSE=${MIDAS_COMPILE_VERBOSE}"
+__job_test_target="make -n ${__target} ${__job_opt}"
+
+##-- lauching dry-run to test target
+echo ${__job_test_target}
+${__job_test_target} > /dev/null 2>&1 || {
+    echo
+    echo "> ${__target}"
+    echo "╔═══════════════════╗"
+    echo "║                   ║"
+    echo "║ INVALID TARGET(S) ║"
+    echo "║                   ║"
+    echo "╚═══════════════════╝"
+    exit 1
+    }
+
+##-- if the dry-run passes, then we define the job adding multi-cores query
+__job="make ${__target} -j ${MIDAS_COMPILE_NCORES} ${__job_opt}"
 
 
 ##=========================================================
